spring:
  datasource:
    port: 5432
    host: localhost
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/hardinv'
    username: postgres
    password: Password25

  security:
    user:
      password: 123

  cache:
    cache-names: settings
    caffeine:
      spec: expireAfterAccess=5s

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
